#include"dagiac.h"
int main(){
    cout<<"=====CHUONG TRINH MINH HOA DA GIAC====="<<endl<<endl;
    cout<<"1. Tao da giac bang cach nhap tu ban phim:"<<endl;
    cDaGiac daGiac1;
    daGiac1.Nhap();
    cout<<"Da giac vua nhap:"<<endl;
    daGiac1.Xuat();
    cout<<"\n2. Tinh toan thuoc tinh co ban:"<<endl;
    cout<<"- Chu vi: "<<daGiac1.TinhChuVi()<<endl;
    cout<<"- Dien tich: "<<daGiac1.TinhDienTich()<<endl;
    cout<<"- "<<daGiac1.KiemTraDaGiacLoi()<<endl;
    cout<<"\n3. Kiem tra diem nam trong da giac: "<<endl<<endl;
    cout<<"Nhap vao diem muon test: "; 
    double fi, se; cin>>fi>>se;
    DIEM diemTest(fi, se);
    cout<<"Diem test "; diemTest.Xuat(); cout<<endl;
    if (daGiac1.KiemTraDiemNamTrong(diemTest)) cout<<"=> Diem nam trong da giac"<<endl;
    else cout<<"=> Diem khong nam trong da giac"<<endl;
    cDaGiac daGiac2(daGiac1);
    cout<<"\n4. Cac phep bien doi da giac:"<<endl<<endl;
    cout<<"Nhap vao toa do x y vector muon tinh tien: "; cin>>fi>>se;
    cout<<"a) Tinh tien theo vector ("<<fi<<", "<<se<<"):" << endl;
    daGiac2.TinhTien(fi, se);
    cout<<"Da giac sau khi tinh tien:"<<endl;
    daGiac2.Xuat();
    cout<<"Nhap vao goc muon quay (0<=goc<=360): ";
    int alpha; cin>>alpha;
    cout<<"b) Quay "<<alpha<<" do quanh goc toa do:"<<endl;
    daGiac2=daGiac1; 
    daGiac2.Quay(alpha);
    cout<<"Da giac sau khi quay:"<<endl;
    daGiac2.Xuat();
    cout<<"Nhap vao ti le muon phong to: ";
    double scale; cin>>scale;
    cout<<"c) Phong to gap "<<scale<<" lan:"<<endl;
    daGiac2=daGiac1; 
    daGiac2.PhongTo(scale);
    cout<<"Da giac sau khi phong to:"<<endl;
    daGiac2.Xuat();
    cout<<"Nhap vao ti le muon thu nho: ";
    cin>>scale;
    cout<<"d) Thu nho xuong "<<scale<<" lan:"<<endl;
    daGiac2=daGiac1; 
    daGiac2.ThuNho(scale);
    cout<<"Da giac sau khi thu nho:"<<endl;
    daGiac2.Xuat();
    cout<<"e) Doi xung qua truc Ox:"<<endl;
    daGiac2=daGiac1; 
    daGiac2.DoiXungOx();
    cout<<"Da giac sau khi doi xung qua Ox:"<<endl;
    daGiac2.Xuat();
    cout<<"f) Doi xung qua truc Oy:"<<endl;
    daGiac2=daGiac1; 
    daGiac2.DoiXungOy();
    cout<<"Da giac sau khi doi xung qua Oy:"<<endl;
    daGiac2.Xuat();
    cout<<"g) Doi xung qua goc toa do:"<<endl;
    daGiac2=daGiac1; 
    daGiac2.DoiXungGoc();
    cout<<"Da giac sau khi doi xung qua goc toa do:"<<endl;
    daGiac2.Xuat();
    cout<<"\n5. Tao da giac tu mang cac diem:"<<endl;
    DIEM dsDiem[4]={DIEM(0, 0), DIEM(4, 0), DIEM(4, 3), DIEM(0, 3)};
    cDaGiac daGiac3(dsDiem, 4);
    cout<<"Da giac hinh chu nhat:"<<endl;
    daGiac3.Xuat();
    cout<<"- Chu vi: "<<daGiac3.TinhChuVi()<<endl;
    cout<<"- Dien tich: "<<daGiac3.TinhDienTich()<<endl;
    cout<<"- "<<daGiac3.KiemTraDaGiacLoi()<<endl;
    cout<<"\n6. Thong ke:"<<endl;
    cout<<"- So luong diem da tao: " << DIEM::GetDem()<<endl;
    cout<<"- So luong da giac da tao: " << cDaGiac::GetDem()<<endl;
    cout<<"\n=== KET THUC CHUONG TRINH ==="<<endl;
    return 0;
}